name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main # or your branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"

          app_location: "webapp/img_upload.html" # root folder with index.html

          output_location: "" # no build step
